# Generated by Django 3.2.7 on 2021-09-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
