# Generated by Django 3.2.7 on 2021-09-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_alter_departamento_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='description',
            field=models.CharField(default='por defecto', max_length=400),
            preserve_default=False,
        ),
    ]
